packages:
  - packages/*

catalogMode: prefer

catalog:
  "@types/node": 22.20.0
  ajv: 8.20.0
  ajv-formats: 3.0.1
  playwright: 1.62.1
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8

peerDependencyRules:
  allowAny:
    - vite
