packages:
  - packages/*

catalogMode: prefer

catalog:
  "@types/node": 22.20.0
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8

peerDependencyRules:
  allowAny:
    - vite
