[package]
name = "rsvite_core"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
axum.workspace = true
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_ast_visit.workspace = true
oxc_parser.workspace = true
oxc_span.workspace = true
percent-encoding.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
